In [50]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, silhouette_samples
import numpy as np
import pandas as pd

In [28]:
def sse(x, c):
    return sum((x - c) ** 2)

def purity(actual, label, arg):
    cluster_purity = {}
    weighted_purity=0
    for k in df[label].unique():
        dom_count = np.max(df[df[label]==k][actual].value_counts())
        size = len(df[df[label]==k])
        cluster_purity[k] = dom_count/size
        weighted_purity += cluster_purity[k]*(size/len(df[label]))
    if arg == 'individual':
        return cluster_purity
    elif arg == 'weighted':
        return weighted_purity

In [29]:
points = {'A':(2,3),
          'B':(7,9),
          'C':(11,4),
          'D':(3,3),
          'E':(14,12),
          'F':(4,5),
          'G':(12,5),
          'H':(9,7),
          'J':(6,4),
          'K':(2,9),
          'L':(4,7),
          'M':(6,8)}

X = np.array(list(points.values()))
X_labels = np.array(list(points.keys())) # global variable used for functions CompiteDistance
df = pd.DataFrame(X)
N=3

In [42]:
kmeans = KMeans(init='k-means++',n_clusters=3).fit(X)
df['label3'] = kmeans.labels_
cluster_sse = np.zeros(len(kmeans.cluster_centers_))

for i in range(len(kmeans.labels_)):
    cluster_sse[kmeans.labels_[i]] = cluster_sse[kmeans.labels_[i]] + sse(X[i], kmeans.cluster_centers_[kmeans.labels_[i]])
sse_cluster = cluster_sse
sse_total = sum(cluster_sse)
    
print('Centroids of the cluster:','\n', kmeans.cluster_centers_)
print('SSE for each cluster', sse_cluster)
print('Sum of the SSE for the clusters:', sse_total)
# print('Purity of each cluster', purity('h', 'label3', 'individual'))
# print('Weighted purity of the entire clustering:', purity('h','label3', 'weighted'))


Centroids of the cluster: 
 [[ 4.75  8.25]
 [ 3.75  3.75]
 [11.5   7.  ]]
SSE for each cluster [17.5 11.5 51. ]
Sum of the SSE for the clusters: 80.0


In [51]:
score = silhouette_score(X, kmeans.labels_, metric='euclidean')
samples = silhouette_samples(X, kmeans.labels_, metric='euclidean')
samples

array([ 0.57051551,  0.42540092,  0.38041029,  0.633037  ,  0.2389146 ,
        0.35440469,  0.48954495, -0.04054421,  0.33559394,  0.3058907 ,
        0.18595659,  0.47758514])

In [46]:
kmeans.labels_

array([1, 0, 2, 1, 2, 1, 2, 2, 1, 0, 0, 0])

In [47]:
kmeans.cluster_centers_

array([[ 4.75,  8.25],
       [ 3.75,  3.75],
       [11.5 ,  7.  ]])

In [13]:
model.inertia_

80.0

In [54]:
from sklearn.metrics import pairwise_distances

In [66]:
xp = [(7,9),(2,9),(4,7),(6,8)]
C = [(4.75, 8.25),(3.75, 3.75),(11.5, 7)]
Ic1 = [(7,9),(2,9),(4,7),(6,8),(2,3),(3,3),(4,5),(6,4)]
Ic2 = [(7,9),(2,9),(4,7),(6,8),(11,4),(14,12),(12,5),(9,7)]

In [67]:
p = pairwise_distances(Ic2)

In [68]:
pd.DataFrame(p)

0          1          2         3          4          5          6  \
0  0.000000   5.000000   3.605551  1.414214   6.403124   7.615773   6.403124   
1  5.000000   0.000000   2.828427  4.123106  10.295630  12.369317  10.770330   
2  3.605551   2.828427   0.000000  2.236068   7.615773  11.180340   8.246211   
3  1.414214   4.123106   2.236068  0.000000   6.403124   8.944272   6.708204   
4  6.403124  10.295630   7.615773  6.403124   0.000000   8.544004   1.414214   
5  7.615773  12.369317  11.180340  8.944272   8.544004   0.000000   7.280110   
6  6.403124  10.770330   8.246211  6.708204   1.414214   7.280110   0.000000   
7  2.828427   7.280110   5.000000  3.162278   3.605551   7.071068   3.605551   

          7  
0  2.828427  
1  7.280110  
2  5.000000  
3  3.162278  
4  3.605551  
5  7.071068  
6  3.605551  
7  0.000000